export PATH=.:$HOME/bin:/data/perl/bin:$PATH
export LD_LIBRARY_PATH=$HOME/lib64:$HOME/lib
#export PKG_CONFIG_PATH=$HOME/lib/pkgconfig
export PERL5LIB=`cat /data/perl/PERL5LIB`
export PYTHONPATH=/home/hesterj/lib/python2.7/site-packages
export DATA_PATH=$HOME/data
export MANPATH=`manpath`:$HOME/share/man
