setopt no_global_rcs

# Cross-platform PATH setup
if [[ "$OSTYPE" == darwin* ]]; then
    # macOS with Homebrew
    export PATH=.:$HOME/bin:/usr/local/opt/ccache/libexec:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:./node_modules/.bin:$HOME/Library/Python/3.7/bin
    #export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
else
    # Linux/WSL
    export PATH=.:$HOME/bin:$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:./node_modules/.bin
fi
#history base for per directory history
export HISTORY_BASE=$HOME/.directory_history
export HISTFILE=$HOME/.zsh_history
export R_KEEP_PKG_SOURCE=yes
#export MAKEFLAGS=-j16

# Workaround for nvim terminal issues with <C-H>
# https://github.com/neovim/neovim/issues/2048#issuecomment-78045837
# infocmp $TERM | sed 's/kbs=^[hH]/kbs=\\177/' > $TERM.ti
# tic $TERM.ti
export TERMINFO="$HOME/.terminfo"
#export NOT_CRAN="true"
