#use updated local zsh rather than builtin
[[ $SHELL != $HOME/bin/zsh ]] && [ -f $HOME/bin/zsh ] && SHELL=$HOME/bin/zsh exec /usr/bin/env $HOME/bin/zsh -l

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.

ZSH_THEME="dst"

ZSH_CUSTOM=$HOME/dotfiles/zsh

export EDITOR=$HOME/bin/vim

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
#COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(vi-mode svn git per-directory-history history-substring-search colemak zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

bindkey '^[OA' history-substring-search-up
bindkey '^[OB' history-substring-search-down

bindkey '^E' history-substring-search-up
bindkey '^N' history-substring-search-down

[ -x "`which lesspipe.sh`" ] && eval "$(lesspipe.sh)"

HISTSIZE=1000000
SAVEHIST=1000000

#fix grep color
unset GREP_COLOR
