setopt global_rcs
TERM=xterm-256color

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.

ZSH_THEME="zhann"

ZSH_CUSTOM=$HOME/dotfiles/zsh

export EDITOR=vim

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
#COMPLETION_WAITING_DOTS="true"

ZSH_TMUX_AUTOSTART=true

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
#per-directory-history 
plugins=(vi-mode
        ant
        svn
        git
        gitignore
        zsh-syntax-highlighting
        history-substring-search
        colemak
        zsh-autosuggestions
        per-directory-history
        autojump
        command-not-found
        jsontools
        tmux)

source $ZSH/oh-my-zsh.sh

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Edit the current command line in $EDITOR
autoload -U edit-command-line
zle -N edit-command-line
bindkey '\C-x\C-e' edit-command-line

HISTSIZE=1000000
SAVEHIST=1000000

#fix grep color
unset GREP_COLOR

AUTOSUGGESTION_HIGHLIGHT_COLOR='fg=250'
autosuggest-start

# bindkey 'FINISH' end_accept
# bindkey '' vi-forward-word-end

 eval `dircolors ~/dotfiles/dircolors/dircolors.ansi-light`

# set cdpath to commonly used directories
# cdpath=( . ~ $HOME/p $HOME/b $HOME/Rpacks )
